### ISSUE TITLE
Fetching the eth 2.0 deposit contract only fetch the metadata

### ISSUE THREAD

**Issue by yann300** [sourcifyeth/remix-sourcify#44]
I tried today to fetch the Eth 2.0 deposit contract (0x00000000219ab540356cbb839cbe05303d7705fa) from the `fetch` section of the plugin.
The metadata.json got imported in the remix file explorer but not the actual source code ( and it looks like the metadata also contain the source code...)

shouldn't the source code be also pushed to Remix?

**Comment by edisinovcic** [comment]
@FabijanC please take a look why only metadata.json is returned. 

From what can be seen here there is both metadata and source files.
https://repo.sourcify.dev/contracts/full_match/1/0x00000000219ab540356cBB839Cbe05303d7705Fa/

**Comment by FabijanC** [comment]
The server returns both `files`. This is the pseudocode of how the `files` are processed in the plugin:
- in `files`, locate `metadata` and other `sources` [(code)](https://github.com/sourcifyeth/remix-sourcify/blob/master/src/remix/RemixClient.ts#L143)
- iterate through the `sources` property of `metadata` [(code)](https://github.com/sourcifyeth/remix-sourcify/blob/master/src/remix/RemixClient.ts#L170)
  - for every `source`, search through its `urls`
  - if there is a `url` addressing ipfs, resolve it and store the file

Sourcify allows `metadata.sources` not to specify `urls`, but directly provide `content`. If only `content` is provided, there is no `urls` property under `metadata.sources[i]`, and the iteration through `urls` fails because it's `undefined`.

### Question
Why does the current implementation resolve ipfs urls instead of using what was fetched from Sourcify?
